sudo: false
language: python, node_js
branches:
  only:
  - main
matrix:
  include:
  - os: linux
notifications:
  email: false
  slack: seniordesigns2021:3lL1Zy8I8gElC5dG6OQlw8Yt
before_script:
- chmod +x ci/setup.sh
- date -u
script:
  - ci/setup.sh
after_success:
  - pip install coveralls
  - coveralls
env:
  global:
    secure: fIvz3eo042SJBjdSuzKrb+D6zpjPlpZlFKFKdF+HsoU/8M8Ekw1KOi/YxJTbQQXHAfU4IEkOmNM27wbNwhabuVXTylIn+svKWS8S9PUZzSk5xzpMrlgVbMj0f8gx4dimfupmx3vAIQCxMWdJoXi1Q5eGTRX9JOf7CID4R/shBZQIZtHp/G3ymq5MHugJMRWLKqctpla0qMJOn6+ey2F1ADCe4WkjnPJsJrZDctsJDclX9CKZq9tRQG5RngLDlqaGpzQTnpbU6sgwEeiBZCqryEVCAKU2ZNhKsWIO+jvEx4/wE8wWQHksFHB428X0moFtVTARDmtI9EIlczMmZglmhBOOjOKzNryWrIGvQCf7/Bl62TFG89zdogCy/Ti2BEuVutBx6oBcILytBhla1pixbYY1ttxYLIl9t2UGMmNKlKv8ZR72l00Pr4HhRwqKuBEA3sOjwsJzlvgX855OZDjTwuIquy6KAkFnc/jWL0vL2Ut+3QCPO6iw32VqmNAu+7me2mYBlkRe5atQzRcfQuvCtsCx7WEVmFQvh2FrrdnpdwyQZatQBsledrG5LfPweoOaBlZTANCEHoeJyph2cMNwOe3IpGKGzjM0g5NrrMich6szcp9IKEInMUf7GtGzZEGTFo3yG62Ol2ZaMsaj2G5fvg40BZN5uXXMEE1crWhYnw0=

