sudo: false
language: python, node_js
branches:
  only:
  - main
matrix:
  include:
  - os: linux
notifications:
  email: false
  slack: seniordesigns2021:3lL1Zy8I8gElC5dG6OQlw8Yt
before_script:
- chmod +x ci/setup.sh
- date -u
script:
  - ci/setup.sh
after_success:
  - pip install coveralls
  - coveralls
env:
  global:
    secure: "T9va5IZXwc8sQkTZIla6F34PQwZ7s4+KZ+cP4P2qALIHn7W88S4cEXzQiNqQcsPMZWxPdAOXEpMo5wbbb4mkgrfjDuBTniCOL6nGMhOOnEg4J3qHZKjYxLf710ayqePbPIB1+pvk9U3q+39tlXI97SItE/oqc9MUcA1CA5ZTRZOfHmvRchDB4k3FOw8ShN/YQwnx2sujU41bNvOY+AcXWs1yXiBIyTfywwUQERFBVYx2j5TgyGIoiqvqcOkXFGv0N+PsybmdsJ7XsLONOfq3KKIRtsBHJiW0k+8T0etmx6lEmghC1MnLY7wns5fdmWnKw9RBP1MyYLsTh0wQHpz49IHO/QqrLizR+7YjapnlESMBfWphwfggH+pL+rJybRhotLUNuj5aImSKsAlwaeHs9mJlIgwIYPIvWgHvUfL5Yp5PazT/1vAZ70gVbe6tRsO05k/CmvPq/X9JMbq/JLGCTw68XOOKm423ejEDkE5lwuHpiuvqgmQYvCsfX3QMHQCSlq1DYV0vwbSzlOfSSvLOhY5vjUuKSOCtqAmujDr1kns9wZZWCuHJyebO9Dehc+OvFiaU8GB+UOpEJFgw1MravF743BNW0tHp6vTjbaEl5BJz/K05y7QQMoALC09FwLd2WSAXdM8NJSmY7Y8G2Zmn1FYcqQ0XMAbhIvLmOwer9tE="
