sudo: false
language: python, node_js
branches:
  only:
  - main
matrix:
  include:
  - os: linux
notifications:
  email: false
  slack: seniordesigns2021:3lL1Zy8I8gElC5dG6OQlw8Yt
before_script:
- chmod +x ci/setup.sh
- date -u
script:
  - ci/setup.sh
after_success:
  - pip install coveralls
  - coveralls
env:
  global:
    secure: fIvz3eo042SJBjdSuzKrb+D6zpjPlpZlFKFKdF+HsoU/8M8Ekw1KOi/YxJTbQQXHAfU4IEkOmNM27wbNwhabuVXTylIn+svKWS8S9PUZzSk5xzpMrlgVbMj0f8gx4dimfupmx3vAIQCxMWdJoXi1Q5eGTRX9JOf7CID4R/shBZQIZtHp/G3ymq5MHugJMRWLKqctpla0qMJOn6+ey2F1ADCe4WkjnPJsJrZDctsJDclX9CKZq9tRQG5RngLDlqaGpzQTnpbU6sgwEeiBZCqryEVCAKU2ZNhKsWIO+jvEx4/wE8wWQHksFHB428X0moFtVTARDmtI9EIlczMmZglmhBOOjOKzNryWrIGvQCf7/Bl62TFG89zdogCy/Ti2BEuVutBx6oBcILytBhla1pixbYY1ttxYLIl9t2UGMmNKlKv8ZR72l00Pr4HhRwqKuBEA3sOjwsJzlvgX855OZDjTwuIquy6KAkFnc/jWL0vL2Ut+3QCPO6iw32VqmNAu+7me2mYBlkRe5atQzRcfQuvCtsCx7WEVmFQvh2FrrdnpdwyQZatQBsledrG5LfPweoOaBlZTANCEHoeJyph2cMNwOe3IpGKGzjM0g5NrrMich6szcp9IKEInMUf7GtGzZEGTFo3yG62Ol2ZaMsaj2G5fvg40BZN5uXXMEE1crWhYnw0=
    secure: "puSODmSoQPeHkj9duv4BvpY9J7BFJ5d1vvW5HCb64ZCYxAfhvOabLCGKBYCynId3LrS5PwxxnhVU3Pd4I2eLUjSY6yS8qfeGTRGiR3BPZmpaO5kLL9JfjcgFSDfBdA52DZ/aepiqgUZzyISzSNkYa/fUOPOcsy4jKQBbG3zC2zXldw83i5jrkzb7l/KmmtF4/CTLdtViCmtO5MbVzZ8z9zmAPlghczmdB53vBQZ1TIK3pVIwsRlUHVYigBPa+11hU/QwMLWPhuDYUuBZwH2Rbn4qgQ5PcMlr/37BHmGUuYOxvEezCC5el74qxL6eXSt24VeKkPmBuI5bl/GhKM4EZHfbxLHM0I7up7A076MHpKKLXuxptt100Y1lwMgE7G0NbYp7cqda9eNptCPoowMGewuxawajyl4s3glhA0fFakYRF3dNUn3FocSi/mNq1zgYtjaYg1ZaC2/lRP6n/4F78XAgvwda2fnX6V9Hw0qkov0yCCyE15mNrQ/dSilX53gJwHf+L0I8BYjDtnMMZygAhs5wz8YfTC0Ulb/7A0FweDSU/T80HA8="
    secure: "MurspaaorwpqsaZra6AKkPVAtjds1YBJN90+2UAglQgxWTxFohDPlZHbvExjfeh2yOZ7rGkG72VgIvALbIrI3E1mqedcFySDJUYBVl3ElL+vzPlv/7LjacIZkC06Ves6Hj4tIJvprzWbGs/pVwWhtKNbK834Nt8KZOHZylJywszLJeVXGAIfsvM/ZBbwVTEYPJTpNVcv41UH1WPTMLg3MPVZeE+ABQmVwv5hysI65AOJQapE51S7cQqSwFm/nUB27k6b6PZCIZFracxSTuZRVqeVbkGks/4HtA6xxygRpotQiG9ORXCMv5xlZmhJ3gAP/88S8o0mIMEPV/8eLmvbxv026G8WZ2QOKF5rYoZpEp5HytLqH1Idhnrmpzg8Pm3GKq6Sfm9gfRRFQ3DHt/KtHkpeEsAHlZv44AE3MMUAL9owcWK1wOqfOvdi9KOpTeNHpblMtYqXE05yXw4dFnyPTqUUOnsYs6kDewpPD4Y9WVX4IGcT1zeSv6EgGpmulDuU+n6nqwTAWFJoibSiU7aq0D9bWU4oK6tuGwr8Iag0lrltYNTxuouTEH6scQoFXfcxQSUP1TOq/4Ao8AmGizTFHcnasCH0DUmnl/RMu2t0pNaxvnOuJLg5FPMW/VhcG95JmxL5j2L+IfwqiY7LJ5zVGK/Z+OHCk2D8at79kz4UWZw="