"""empty message

Revision ID: 26c8eb692238
Revises: ed657e16ce20
Create Date: 2021-02-16 13:43:49.906080

"""

# revision identifiers, used by Alembic.
revision = '26c8eb692238'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
